/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/auth/login': RouteRecordInfo<'/auth/login', '/auth/login', Record<never, never>, Record<never, never>>,
    '/settings': RouteRecordInfo<'/settings', '/settings', Record<never, never>, Record<never, never>>,
    '/settings/courses': RouteRecordInfo<'/settings/courses', '/settings/courses', Record<never, never>, Record<never, never>>,
    '/settings/generations': RouteRecordInfo<'/settings/generations', '/settings/generations', Record<never, never>, Record<never, never>>,
    '/settings/generations/': RouteRecordInfo<'/settings/generations/', '/settings/generations', Record<never, never>, Record<never, never>>,
    '/settings/generations/[id]': RouteRecordInfo<'/settings/generations/[id]', '/settings/generations/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/settings/generations/[id]/': RouteRecordInfo<'/settings/generations/[id]/', '/settings/generations/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/settings/generations/[id]/update': RouteRecordInfo<'/settings/generations/[id]/update', '/settings/generations/:id/update', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/settings/generations/create': RouteRecordInfo<'/settings/generations/create', '/settings/generations/create', Record<never, never>, Record<never, never>>,
    '/settings/majors': RouteRecordInfo<'/settings/majors', '/settings/majors', Record<never, never>, Record<never, never>>,
    '/settings/majors/': RouteRecordInfo<'/settings/majors/', '/settings/majors', Record<never, never>, Record<never, never>>,
    '/settings/majors/[id]': RouteRecordInfo<'/settings/majors/[id]', '/settings/majors/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/settings/majors/[id]/': RouteRecordInfo<'/settings/majors/[id]/', '/settings/majors/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/settings/majors/[id]/update': RouteRecordInfo<'/settings/majors/[id]/update', '/settings/majors/:id/update', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/settings/majors/create': RouteRecordInfo<'/settings/majors/create', '/settings/majors/create', Record<never, never>, Record<never, never>>,
    '/settings/room/': RouteRecordInfo<'/settings/room/', '/settings/room', Record<never, never>, Record<never, never>>,
    '/settings/room/[id]': RouteRecordInfo<'/settings/room/[id]', '/settings/room/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/settings/room/[id]/': RouteRecordInfo<'/settings/room/[id]/', '/settings/room/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/settings/room/[id]/update': RouteRecordInfo<'/settings/room/[id]/update', '/settings/room/:id/update', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/settings/room/create': RouteRecordInfo<'/settings/room/create', '/settings/room/create', Record<never, never>, Record<never, never>>,
    '/settings/room copy/': RouteRecordInfo<'/settings/room copy/', '/settings/room copy', Record<never, never>, Record<never, never>>,
    '/settings/room copy/[id]': RouteRecordInfo<'/settings/room copy/[id]', '/settings/room copy/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/settings/room copy/[id]/': RouteRecordInfo<'/settings/room copy/[id]/', '/settings/room copy/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/settings/room copy/[id]/update': RouteRecordInfo<'/settings/room copy/[id]/update', '/settings/room copy/:id/update', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/settings/room copy/create': RouteRecordInfo<'/settings/room copy/create', '/settings/room copy/create', Record<never, never>, Record<never, never>>,
    '/settings/rooms': RouteRecordInfo<'/settings/rooms', '/settings/rooms', Record<never, never>, Record<never, never>>,
    '/settings/students': RouteRecordInfo<'/settings/students', '/settings/students', Record<never, never>, Record<never, never>>,
    '/settings/students/': RouteRecordInfo<'/settings/students/', '/settings/students', Record<never, never>, Record<never, never>>,
    '/settings/students/[id]': RouteRecordInfo<'/settings/students/[id]', '/settings/students/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/settings/students/[id]/': RouteRecordInfo<'/settings/students/[id]/', '/settings/students/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/settings/students/[id]/update': RouteRecordInfo<'/settings/students/[id]/update', '/settings/students/:id/update', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/settings/students/create': RouteRecordInfo<'/settings/students/create', '/settings/students/create', Record<never, never>, Record<never, never>>,
    '/settings/teachers': RouteRecordInfo<'/settings/teachers', '/settings/teachers', Record<never, never>, Record<never, never>>,
    '/settings/teachers/': RouteRecordInfo<'/settings/teachers/', '/settings/teachers', Record<never, never>, Record<never, never>>,
    '/settings/teachers/[id]': RouteRecordInfo<'/settings/teachers/[id]', '/settings/teachers/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/settings/teachers/[id]/': RouteRecordInfo<'/settings/teachers/[id]/', '/settings/teachers/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/settings/teachers/[id]/update': RouteRecordInfo<'/settings/teachers/[id]/update', '/settings/teachers/:id/update', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/settings/teachers/create': RouteRecordInfo<'/settings/teachers/create', '/settings/teachers/create', Record<never, never>, Record<never, never>>,
  }
}
