/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/auth/login': RouteRecordInfo<'/auth/login', '/auth/login', Record<never, never>, Record<never, never>>,
    '/settings': RouteRecordInfo<'/settings', '/settings', Record<never, never>, Record<never, never>>,
    '/settings/generations': RouteRecordInfo<'/settings/generations', '/settings/generations', Record<never, never>, Record<never, never>>,
    '/settings/generations.create': RouteRecordInfo<'/settings/generations.create', '/settings/generations/create', Record<never, never>, Record<never, never>>,
    '/settings/students': RouteRecordInfo<'/settings/students', '/settings/students', Record<never, never>, Record<never, never>>,
    '/settings/students.create': RouteRecordInfo<'/settings/students.create', '/settings/students/create', Record<never, never>, Record<never, never>>,
    '/settings/teachers': RouteRecordInfo<'/settings/teachers', '/settings/teachers', Record<never, never>, Record<never, never>>,
    '/settings/teachers.create': RouteRecordInfo<'/settings/teachers.create', '/settings/teachers/create', Record<never, never>, Record<never, never>>,
  }
}
